version: '3.3'
services:
  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
      - .:/var/www/enchere
      - ./site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
  php:
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/php/DockerFile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - .:/var/www/enchere
  mercure:
    container_name: mercure
    restart: unless-stopped
    image: dunglas/mercure:v0.10.4
    environment:
      CORS_ALLOWED_ORIGINS: 'http://localhost:8000'
      JWT_KEY: 'ChangeMe'
      ALLOW_ANONYMOUS: 1
    ports:
      - 3001:80
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:latest
    environment:
      MEILI_MASTER_KEY: 123
    volumes:
      - ./data.ms:/var/www/enchere/data.ms
    ports:
      - 7700:7700
  node:
    user: '${USER_ID}:${GROUP_ID}'
    image: node:10.23-alpine
    command: yarn run dev
    working_dir: /var/www/enchere
    volumes:
      - .:/var/www/enchere
    ports:
      - 3000:3000